// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHprTFCYOugNo2gMwqb-vFdj3n8FbUno',
    appId: '1:411696594284:web:01c48f2c66fd13db0f0749',
    messagingSenderId: '411696594284',
    projectId: 'meal-prep-app-fba42',
    authDomain: 'meal-prep-app-fba42.firebaseapp.com',
    storageBucket: 'meal-prep-app-fba42.firebasestorage.app',
    measurementId: 'G-L05M2RDRMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pjhwAvI8fuXx84hnV8OcEXjrcerovQs',
    appId: '1:411696594284:android:8b42f008c686d2e50f0749',
    messagingSenderId: '411696594284',
    projectId: 'meal-prep-app-fba42',
    storageBucket: 'meal-prep-app-fba42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlH7Zx8iRekXY5NnLRnICTCU64YXCO2Xo',
    appId: '1:411696594284:ios:593fa2df3a1c021e0f0749',
    messagingSenderId: '411696594284',
    projectId: 'meal-prep-app-fba42',
    storageBucket: 'meal-prep-app-fba42.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlH7Zx8iRekXY5NnLRnICTCU64YXCO2Xo',
    appId: '1:411696594284:ios:593fa2df3a1c021e0f0749',
    messagingSenderId: '411696594284',
    projectId: 'meal-prep-app-fba42',
    storageBucket: 'meal-prep-app-fba42.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWHprTFCYOugNo2gMwqb-vFdj3n8FbUno',
    appId: '1:411696594284:web:7c7e5c172e9789e80f0749',
    messagingSenderId: '411696594284',
    projectId: 'meal-prep-app-fba42',
    authDomain: 'meal-prep-app-fba42.firebaseapp.com',
    storageBucket: 'meal-prep-app-fba42.firebasestorage.app',
    measurementId: 'G-17GLCQKCN7',
  );
}
